name: Generate blog post

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc if not available
        run: |
          if ! command -v pandoc &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pandoc
          fi

      - name: Generate blog post from commits
        run: |
          python3 generate_blogs.py
          echo "Generated blog post from commits."

      - name: Display content of index.html
        run: cat index.html

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - uses: actions/checkout@v3

      - name: Create blog-posts directory if not available
        run: |
          if [ ! -d "/var/www/html/blog-posts" ]; then
            sudo mkdir -p /var/www/html/blog-posts
            sudo chown -R $USER:$USER /var/www/html/blog-posts
            echo "Created /var/www/html/blog-posts directory."
          fi

      - name: Copy index.html to the destination directory
        run: cp index.html /var/www/html/blog-posts
        shell: bash

      - name: Display files in the destination directory
        run: ls -l /var/www/html/blog-posts

      - name: Display content of index.html on the website
        run: cat /var/www/html/blog-posts/index.html
