name: Generate and Publish Dev Blogs

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install gitpython markdown2

      - name: Generate blog post from commits
        run: |
          python3 generate_blogs.py

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - name: Install Apache web server
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          
      - name: Print files and folders in the directory
        run: |
          cd /var/www/html
          ls -R
        
      - name: Publish blog post
        run: |
          cd /var/www/html
      
          echo "Current directory:"
          pwd
        
          echo "List files and folders in the current directory:"
          ls -R
      
          echo "Publishing blog post..."
          echo "<!-- Blog post content -->" | sudo tee -a blogs_auto.html
          cat blogs_auto.html | sudo tee -a blogs_auto.html
          echo "<!-- End of blog post content -->" | sudo tee -a blogs_auto.html
          echo "Blog post published successfully."
        
        

      - name: List files in the destination directory
        run: ls -l /var/www/html/

      - name: Display content of blogs_auto.html
        run: cat /var/www/html/blogs_auto.html

      - name: Display content of blog_post.html (optional - for debugging)
        run: |
          cd /var/www/html 
          cat blogs_auto.html

