name: Generate Blog Post

on:
  push:
    branches:
      - gh-pages  # Change this if your main branch has a different name

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.103'  # Change to your preferred .NET Core version

      - name: Install dependencies
        run: dotnet restore

      - name: Build and run script
        run: |
          dotnet build -c Release
          dotnet run --project FunnyRacing/Assembly-CSharp.csproj
