name: Generate blog post

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pandoc if not available
        run: |
          if ! command -v pandoc &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y pandoc
          fi

      - name: Ensure blog_post.md exists
        run: |
          if [ ! -f "blog_post.md" ]; then
            # Define the blog_post.md template
            cat <<EOF > blog_post.md
# My Blog Post

This is a sample blog post created using GitHub Actions and Pandoc.

## Section 1

This is the first section of the blog post.

## Section 2

This is the second section of the blog post.
EOF
            echo "Created blog_post.md file from template."
          fi

      - name: Generate blog post
        run: |
          echo "Generating blog post..."
          pandoc -s -f markdown -t html blog_post.md -o blog_post.html
          if [ -f "blog_post.html" ]; then
            echo "HTML file generated successfully."
          else
            echo "Failed to generate the HTML file."
            touch blog_post.html
            echo "Created an empty blog_post.html file."
          fi
          ls -l

      - name: Upload blog post
        uses: actions/upload-artifact@v2
        with:
          name: blog_post
          path: blog_post.html

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - uses: actions/checkout@v3
      - name: Create blog-posts directory if not available
        run: |
          if [ ! -d "/var/www/html/blog-posts" ]; then
            sudo mkdir -p /var/www/html/blog-posts
            sudo chown -R $USER:$USER /var/www/html/blog-posts
            echo "Created /var/www/html/blog-posts directory."
          fi

      - name: Display files in the current directory
        run: ls -l

      - name: Download blog post artifact
        uses: actions/download-artifact@v2
        with:
          name: blog_post
          path: blog_post_artifact

      - name: Display files in the downloaded artifact
        run: ls -l blog_post_artifact

      - name: Publish blog post
        run: |
          echo "Publishing blog post..."
          if [ -f "blog_post_artifact/blog_post.html" ]; then
            cp blog_post_artifact/blog_post.html /var/www/html/blog-posts
            echo "Blog post published successfully."
          else
            echo "Failed to find the HTML file in the artifact."
          fi

      - name: List files in the destination directory
        run: ls -l /var/www/html/blog-posts

      - name: Display content of blog_post.html
        run: cat /var/www/html/blog-posts/blog_post.html
