name: Generate blog post

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Generate blog post
        run: |
          echo "Generating blog post..."
          if [ -f "blog_post.md" ]; then
            echo "Blog post already exists."
          else
            touch blog_post.md
            echo "Created blog post file."
          fi
          pandoc -s -f markdown -t html blog_post.md -o blog_post.html
          if [ -f "blog_post.html" ]; then
            echo "HTML file generated successfully."
          else
            echo "Failed to generate the HTML file."
          fi

      - name: Display files in the current directory
        run: ls -l

      - name: Upload blog post
        uses: actions/upload-artifact@v2
        with:
          name: blog_post
          path: blog_post.html

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - uses: actions/checkout@v3
      - name: Display files in the current directory
        run: ls -l
      - name: Publish blog post
        run: |
          echo "Publishing blog post..."
          cp blog_post.html /var/www/html/blog-posts
