name: Generate blog post

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate blog post
        run: |
          echo "Generating blog post..."
          pandoc -s -f markdown -t html blog_post.md -o blog_post.html

      - name: Upload blog post
        uses: actions/upload-artifact@v1
        with:
          name: blog_post
          path: blog_post.html

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - uses: actions/checkout@v3
      - name: Publish blog post
        run: |
          echo "Publishing blog post..."
          cp blog_post.html /var/www/html