name: Generate and Publish Dev Blogs

on:
  push:
    branches:
      - gh-pages

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install gitpython markdown2

      - name: Generate blog post from commits
        run: |
          python3 generate_blogs.py

  publish-blog-post:
    runs-on: ubuntu-latest
    needs: generate-blog-post
    steps:
      - name: Install Apache web server
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2
          
      - name: Print files and folders in the directory
        run: |
          cd /var/www/html
          ls -R
        
      - name: Publish blog post
        run: |
          echo "Publishing blog post..."
          cp $GITHUB_WORKSPACE/index.html /github/workspace/var/www/html/
          echo "<!-- Blog post content -->" >> /github/workspace/var/www/html/index.html
          cat /github/workspace/var/www/html/index.html >> /github/workspace/var/www/html/index.html
          cat /var/www/html/blog-posts/blog_post.html >> /github/workspace/var/www/html/index.html
          echo "<!-- End of blog post content -->" >> /github/workspace/var/www/html/index.html
          mv /github/workspace/var/www/html/index.html /github/workspace/index.html
          echo "Blog post published successfully."

      - name: List files in the destination directory
        run: ls -l /var/www/html/

      - name: Display content of index.html
        run: cat /var/www/html/index.html

      - name: Display content of blog_post.html (optional - for debugging)
        run: cat index.html

